#!/usr/bin/env python3
"""Regenerate the Universal Triage router and the playbook catalogue.

The router is the block in trees/universal-triage.yaml between the
BEGIN/END GENERATED ROUTER markers. It holds a category menu (ch-route),
one menu per category listing every playbook in it, and a link node per
playbook. docs/CATALOGUE.md lists every playbook with its alert names and
ATT&CK techniques.

Run it after adding, renaming or removing a tree:
    python tools/gen_router.py
CI runs it with --check and fails if either file is stale.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate import ROOT, load_trees  # noqa: E402

ROUTER_FILE = ROOT / "trees" / "universal-triage.yaml"
CATALOGUE_FILE = ROOT / "docs" / "CATALOGUE.md"
BEGIN = "  # BEGIN GENERATED ROUTER (python tools/gen_router.py)"
END = "  # END GENERATED ROUTER"
CATEGORIES = [
    ("email", "Email and collaboration", "Which email or collaboration alert?"),
    ("identity", "Identity: Entra ID and Active Directory", "Which identity alert?"),
    ("endpoint", "Endpoint: Windows, Linux and servers", "Which endpoint alert?"),
    ("network", "Network, perimeter and OT", "Which network, perimeter or OT alert?"),
    ("cloud", "Cloud and SaaS: Azure, AWS and M365 data", "Which cloud or SaaS alert?"),
]


def q(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_router(trees: dict) -> str:
    lines = [BEGIN]
    lines += [
        "  ch-route:",
        "    type: choice",
        "    text: Which kind of alert is this?",
        "    why: A dedicated playbook asks the questions that matter for that alert type. Use the generic path only if none fits.",
        "    options:",
    ]
    for cat, label, _ in CATEGORIES:
        count = sum(1 for t in trees.values() if t["category"] == cat)
        if count:
            lines.append("      - { label: " + q(f"{label} ({count})") + f", next: ch-{cat} }}")
    lines.append('      - { label: "None of these: use the generic flow", next: q-obviously-benign }')
    lines.append("")
    for cat, label, question in CATEGORIES:
        members = sorted((t for t in trees.values() if t["category"] == cat), key=lambda t: t["title"])
        if not members:
            continue
        lines += [
            f"  ch-{cat}:",
            "    type: choice",
            "    text: " + q(question),
            "    options:",
        ]
        for t in members:
            lines.append(f"      - {{ label: {q(t['title'])}, next: l-{t['id']} }}")
        lines.append('      - { label: "None of these: use the generic flow", next: q-obviously-benign }')
        lines.append("")
    for t in sorted(trees.values(), key=lambda t: t["id"]):
        if t["category"] == "triage":
            continue
        lines.append(f"  l-{t['id']}: {{ type: link, text: {q('Continue in ' + t['title'])}, tree: {t['id']} }}")
    lines.append(END)
    return "\n".join(lines)


def build_catalogue(trees: dict) -> str:
    out = [
        "# Playbook catalogue",
        "",
        "Generated by `python tools/gen_router.py`. Do not edit by hand.",
        "",
        f"{len(trees)} playbooks.",
        "",
    ]
    for cat, label in [("triage", "Start here")] + [(c, l) for c, l, _ in CATEGORIES]:
        members = sorted((t for t in trees.values() if t["category"] == cat), key=lambda t: t["title"])
        if not members:
            continue
        out += [f"## {label} ({len(members)})", "", "| Playbook | Typical alert names | ATT&CK |", "|---|---|---|"]
        for t in members:
            alerts = "; ".join(t.get("applies_to", [])[:3]).replace("|", "/")
            mitre = ", ".join(t.get("mitre", []))
            out.append(f"| [{t['title']}](../trees/{t['id']}.yaml) | {alerts} | {mitre} |")
        out.append("")
    return "\n".join(out)


def main() -> int:
    check = "--check" in sys.argv
    trees, errors = load_trees(ROOT / "trees")
    if errors:
        print("\n".join(errors))
        return 1

    text = ROUTER_FILE.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        print(f"Router markers missing from {ROUTER_FILE.name}")
        return 1
    a = text.index(BEGIN)
    b = text.index(END) + len(END)
    new_text = text[:a] + build_router(trees) + text[b:]
    new_cat = build_catalogue(trees)

    stale = []
    if new_text != text:
        stale.append(str(ROUTER_FILE.relative_to(ROOT)))
    if not CATALOGUE_FILE.exists() or CATALOGUE_FILE.read_text(encoding="utf-8") != new_cat:
        stale.append(str(CATALOGUE_FILE.relative_to(ROOT)))

    if check:
        if stale:
            print("Out of date, run python tools/gen_router.py: " + ", ".join(stale))
            return 1
        print("Router and catalogue are up to date.")
        return 0

    ROUTER_FILE.write_text(new_text, encoding="utf-8")
    CATALOGUE_FILE.parent.mkdir(exist_ok=True)
    CATALOGUE_FILE.write_text(new_cat, encoding="utf-8")
    print(f"Updated {', '.join(stale) if stale else 'nothing (already current)'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
